spring:
  application:
    name: rilcomar

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=RILCOMAR;trustServerCertificate=true;
    username: sa
    password: Admin123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  qr:
    url: http://localhost:3000/pallets/

server:
  port: 8085
  servlet:
    context-path: /rilcomar