spring:
  application:
    name: rilcomar

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=RILCOMAR;trustServerCertificate=true;
    username: rilcomar
    password: pallet-2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: 8085
  servlet:
    context-path: /rilcomar